// Flat ESLint config (ESLint 9). The generated client under src/_generated/ is
// regenerated by @hey-api/openapi-ts on every backend sync, so it is excluded
// from linting to avoid diff noise on regen.
import js from "@eslint/js";
import tseslint from "@typescript-eslint/eslint-plugin";
import tsparser from "@typescript-eslint/parser";

export default [
  {
    ignores: ["dist/**", "node_modules/**", "src/_generated/**", "coverage/**"],
  },
  js.configs.recommended,
  {
    // Plain-JS Node scripts (config files, build helpers like sync-version.mjs)
    // run under Node, so expose its globals.
    files: ["**/*.{js,mjs,cjs}"],
    languageOptions: {
      globals: { console: "readonly", process: "readonly" },
    },
  },
  {
    files: ["**/*.ts"],
    languageOptions: {
      parser: tsparser,
      parserOptions: { ecmaVersion: 2022, sourceType: "module" },
    },
    plugins: { "@typescript-eslint": tseslint },
    rules: {
      ...tseslint.configs.recommended.rules,
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/explicit-module-boundary-types": "off",
      // TypeScript already resolves identifiers (incl. DOM/Node globals like
      // fetch, Request, Blob), so no-undef is redundant and noisy here. This is
      // the typescript-eslint-recommended setting for typed code.
      "no-undef": "off",
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
    },
  },
];
